# Generated by Django 5.2.6 on 2025-11-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('gerente_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('esta_ativa', models.BooleanField(default=True, help_text='Indica se a filial está ativa')),
            ],
        ),
    ]
